In [52]:
import pandas as pd 
import numpy as np
import seaborn as sns

In [53]:
df = sns.load_dataset('penguins')
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

In [54]:
df.shape

(344, 7)

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


In [56]:
df.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [57]:
df.dropna(inplace=True)

In [58]:
df.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

###  one hot encoding tranformation

In [59]:
df.sex.unique()

array(['Male', 'Female'], dtype=object)

In [60]:
pd.get_dummies(df['sex']).head()

Female  Male
0       0     1
1       1     0
2       1     0
4       1     0
5       0     1

In [61]:
sex = pd.get_dummies(df['sex'],drop_first=True)

In [62]:
sex.head()

Male
0     1
1     0
2     0
4     0
5     1

In [63]:
df.island.unique()

array(['Torgersen', 'Biscoe', 'Dream'], dtype=object)

In [64]:
pd.get_dummies(df['island']).head()

Biscoe  Dream  Torgersen
0       0      0          1
1       0      0          1
2       0      0          1
4       0      0          1
5       0      0          1

In [65]:
island = pd.get_dummies(df['island'],drop_first = True)
island.head(5)

Dream  Torgersen
0      0          1
1      0          1
2      0          1
4      0          1
5      0          1

In [78]:
data1 = pd.concat([df,island,sex],axis =1)


In [79]:
data1.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
4  Adelie  Torgersen            36.7           19.3              193.0   
5  Adelie  Torgersen            39.3           20.6              190.0   

   body_mass_g     sex  Dream  Torgersen  Male  
0       3750.0    Male      0          1     1  
1       3800.0  Female      0          1     0  
2       3250.0  Female      0          1     0  
4       3450.0  Female      0          1     0  
5       3650.0    Male      0          1     1

In [80]:
data1.drop(['sex','island'],axis=1,inplace=True);

In [81]:
data1.head()

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0  Adelie            39.1           18.7              181.0       3750.0   
1  Adelie            39.5           17.4              186.0       3800.0   
2  Adelie            40.3           18.0              195.0       3250.0   
4  Adelie            36.7           19.3              193.0       3450.0   
5  Adelie            39.3           20.6              190.0       3650.0   

   Dream  Torgersen  Male  
0      0          1     1  
1      0          1     0  
2      0          1     0  
4      0          1     0  
5      0          1     1

# CREATING SEPARATE TARGET VARIABLE

In [82]:
y = data1.species
y.head()

0    Adelie
1    Adelie
2    Adelie
4    Adelie
5    Adelie
Name: species, dtype: object

In [83]:
y.unique()

array(['Adelie', 'Chinstrap', 'Gentoo'], dtype=object)

In [84]:
y = y.map({'Adelie': 0,'Chinstrap':1,'Gentoo':2})
y.head()


0    0
1    0
2    0
4    0
5    0
Name: species, dtype: int64

In [85]:
data1.drop('species',inplace=True,axis=1)

In [86]:
data1.head()

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  Dream  \
0            39.1           18.7              181.0       3750.0      0   
1            39.5           17.4              186.0       3800.0      0   
2            40.3           18.0              195.0       3250.0      0   
4            36.7           19.3              193.0       3450.0      0   
5            39.3           20.6              190.0       3650.0      0   

   Torgersen  Male  
0          1     1  
1          1     0  
2          1     0  
4          1     0  
5          1     1

In [87]:
x = data1

In [88]:
from sklearn.model_selection import train_test_split

In [89]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [90]:
print('x_train',x_train.shape)
print('x_test',x_test.shape)
print('y_train' ,y_train.shape)
print('y_test',y_test.shape)

x_train (233, 7)
x_test (100, 7)
y_train (233,)
y_test (100,)


In [95]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 5 ,criterion = 'entropy',random_state = 0)
classifier.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=5, random_state=0)

PREDICTING THE RESULT 

In [96]:
y_pred = classifier.predict(x_test)

In [97]:
y_pred

array([0, 0, 2, 0, 0, 0, 1, 2, 2, 1, 2, 0, 0, 1, 0, 0, 2, 0, 1, 0, 0, 0,
       2, 2, 2, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 1, 0, 1, 0, 2, 2, 0, 0,
       0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0, 1, 0, 2, 0, 0,
       2, 2, 1, 2, 2, 1, 2, 1, 0, 2, 0, 2, 0, 2, 1, 2, 2, 2, 1, 2, 1, 0,
       0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 2, 2], dtype=int64)

# CONFUSION MATRIX

In [100]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report,accuracy_score

In [101]:
cm = confusion_matrix(y_test,y_pred)

In [102]:
print(cm)

[[48  0  0]
 [ 2 14  0]
 [ 0  0 36]]


In [103]:
accuracy_score(y_test,y_pred)

0.98

In [104]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98        48
           1       1.00      0.88      0.93        16
           2       1.00      1.00      1.00        36

    accuracy                           0.98       100
   macro avg       0.99      0.96      0.97       100
weighted avg       0.98      0.98      0.98       100



# try with different numbers of trees and gini criteria

In [105]:
classifier = RandomForestClassifier(n_estimators = 7 ,criterion = 'gini',random_state=0)

In [107]:
classifier.fit(x_train,y_train)

RandomForestClassifier(n_estimators=7, random_state=0)

In [109]:
y_pred  = classifier.predict(x_test)

In [110]:
accuracy_score(y_test,y_pred)

0.99